### ISSUE TITLE
"File clean" result for any file

### ISSUE THREAD

**Issue by sahil-lakhwani** [tekmaven/nClam#11]
The project runs clean and good,  but it gives a "File clean" result for any file. I tried scanning the EICAR sample file. When scanning the same file with clamscan.exe I get the expected result. I checked the clamd.conf file, I have specified the database as C:\Program Files\ClamAV\db, which is the same what I use for clamscan.

I understand that this query is a bit irrelevant to your project but I would really appreciate your help. Thanks.

**Comment by tekmaven** [comment]
Can you provide a code sample?

**Comment by sahil-lakhwani** [comment]
Sir it is tge same example code you have provided in thw read me file

**Comment by sahil-lakhwani** [comment]
I re-installed the service, build the config file again, and it is working fine now :+1: Thanks a lot for this project and for your concern Sir.
