### ISSUE TITLE
When to use the multi thread option?

### ISSUE THREAD

**Issue by sahil-lakhwani** [tekmaven/nClam#13]
There's another function `ScanFileOnServerMultithreaded`
I would appreciate any advice on when to use it and when not.
Thank you.

**Comment by tekmaven** [comment]
`ScanFileOnServerMultithreaded` calls ClamAV with `multiscan`.

From http://linux.die.net/man/1/clamdscan:

> In the multiscan mode clamd will attempt to scan the directory contents in parallel using available threads. This option is especially useful on multiprocessor and multi-core systems. If you pass more than one file or directory in the command line, they are put in a queue and sent to clamd individually. This means, that single files are always scanned by a single thread. Similarly, clamdscan will wait for clamd to finish a directory scan (performed in multiscan mode) before sending request to scan another directory. This option can be combined with --fdpass (see below).
