### ISSUE TITLE
Using nClam to scan images on external sites.

### ISSUE THREAD

**Issue by nueverest** [tekmaven/nClam#14]
Is it possible to use the clam client to test files located on Amazon S3, Cloudfront, or on a website "not" running on the windows server?

**Comment by tekmaven** [comment]
All you would need to do is download the file into a `Stream` object (or `byte[]`) in memory and then pass it to the `SendAndScanFile(Stream sourceStream)` or `SendAndScanFile(byte[] fileData)` methods of `ClamClient`.

**Comment by nueverest** [comment]
Stream worked for me thanks.
