### ISSUE TITLE
Non-localhost Implementation

### ISSUE THREAD

**Issue by nueverest** [tekmaven/nClam#15]
I attempted to implement a solution were the `ClamClient` uses a public url. 

I changed the example code line From:
`var clam = new ClamClient("localhost", 3310);`

To: 
`var clam = new ClamClient("https://somedomain.com/", 3310);`

I also:
Installed and started both ClamAV services on the server.
Tested with the "localhost" option (works great).
Opened port 3310 on `somedomain.com` server.

But it does not work when something other than "localhost" is used. Any ideas on what I'm doing incorrect, or whether this is even an intended use case?

**Comment by tekmaven** [comment]
The client should take a hostname and not a URL, so try:
```csharp
var clam = new ClamClient("somedomain.com", 3310);
```

Obviously the port 3310 needs to be accessible remotely.  You can check this with telnet.

**Comment by nueverest** [comment]
Thank you for the reminder about telnet.  I also found [http://www.canyouseeme.org/](http://www.canyouseeme.org/) to be helpful.

Since I'm using AWS it turned out to be harder than just opening 3310 on my windows Firewall.

I had to: 

- Open the port on my Load Balancer security group.
- Add a listener to the load balancer.
- Open the port on my EC2 server security group.
