### ISSUE TITLE
Directory/File is not found!

### ISSUE THREAD

**Issue by BryceTheCoder** [tekmaven/nClam#17]
Hello there!:)
Just installed ClamAV server on my dedicated Windows 7 server and that is 100% properly installed.
However, when I test the application in my C# project using this:
`private void button1_Click(object sender, EventArgs e) {
            OpenFileDialog open = new OpenFileDialog();
            if (open.ShowDialog() == DialogResult.OK) {

                MessageBox.Show(open.FileName);

                ClamClient client = new ClamClient("Oops!HidingMyIP", 3310);
                //ClamScanResult res = client.ScanFileOnServer(open.FileName);
                ClamScanResult res = client.ScanFileOnServer("C:\\test.txt");

                switch (res.Result) {
                    case ClamScanResults.Clean:
                        MessageBox.Show("Clean");
                        break;
                    case ClamScanResults.VirusDetected:
                        MessageBox.Show("Virus found: " + res.InfectedFiles.First().VirusName);
                        break;
                    case ClamScanResults.Error:
                        MessageBox.Show("Error: " + res.RawResult);
                        break;
                }

            }

            
        }`

I have a text file and the file exists on  C:\test.txt
However it keeps giving ClamScanResults.Error and saying:
"Error: \\?\C:\test.txt lstat() failed: No such file or directory. ERROR

How can I fix this? The directory is correct and the file exists, however it keeps saying it does not. :(
Please help me out :'c

**Comment by tekmaven** [comment]
Is the app running on the same machine as the server?  Does the ClamAV service have permissions to the file?  Try to switch to `SendAndScanFile` and see if that works.

**Comment by BryceTheCoder** [comment]
Changed to SendAndScanFile, works perfectly!
Sorry, did not see that method :(
Thanks for the help!
