### ISSUE TITLE
Porting to .net core

### ISSUE THREAD

**Issue by andycwk** [tekmaven/nClam#18]
Hi,

I'm going to be investigating the use of ClamAV from within a docker container so I can scale out as needed to cope with demand!

I'm going to be creating a .net core project that will orchestrate the scan process and sit within the docker image... I would like to use nClam as part of the solution... any objections to me creating a pull request at the end?

Cheers!

**Comment by tekmaven** [comment]
Thanks for your interest in nClam!  I would love the pull request.  It should be very simple to convert the library to .NET Core.  Please make sure we also support .NET Framework as a part of the same NuGet package so we don't break existing users.

I can push this to our official NuGet package once you are done.

**Comment by andycwk** [comment]
Cool... It's a lower priority project among the many things I have to do.. so will probably be a few weeks before I'm done... watch this space and cheers :)
