### ISSUE TITLE
v3.0.0 Breaks existing synchronous scanning

### ISSUE THREAD

**Issue by uncled1023** [tekmaven/nClam#20]
While async scanning is nice, I want to be able to synchronously scan files, but now I have to add the async wrapper.  Is there a reason the old method was removed?

**Comment by bobs619** [comment]
re-add the sync methods pretty please

**Comment by tekmaven** [comment]
The library has been feature complete for many years and the latest non-async release is 100% the same functionality as the current release with async.  

TLDR:  Just use the release you were always using.
