### ISSUE TITLE
Upgrade ClamAv in Windows

### ISSUE THREAD

**Issue by MaitriSejpal** [tekmaven/nClam#21]
I have ClamAv is on my VM(Virtual Machine).

In My live site(Made in MVC Framewrok) , to scan Cv i am using ClamAv. now i want to upgrade ClamAv.

but i am not understanding by, it is to simply update the nclam Nudget Package or anything else?

and if i update that will it be effect on live site?

**Comment by tekmaven** [comment]
This is a ClamAV engine question.  Perhaps address this with the ClamAV maintainers.

If this is about nClam, reopen the issue.
