### ISSUE TITLE
nClam for .net standard 1.6

### ISSUE THREAD

**Issue by imran2489** [tekmaven/nClam#24]
Hi My project is using .net standard version 1.6.

If i try to use nClam it refuses to install as it is incompatible with .net standard 1.6. 

Do we have any other version of nclam that supports .net standard 1.6 ?

**Comment by tekmaven** [comment]
Hello @imran2489 - unfortunately, we won't support .NET Standard 1.6 in this project.  However, I have good news, the project itself is VERY simple (mostly contained in 1 file) and you can just take the source and make modifications on 1-2 lines to have it compile in netstandard1.6.  All of the logic is in `ClamClient.cs` - https://github.com/tekmaven/nClam/blob/master/nClam/ClamClient.cs.  There are a few other files for POCOs and exceptions, and you can grab them too.  I hope this helps!

**Comment by imran2489** [comment]
Thanks a bunch. I will have a look 😊

________________________________
