### ISSUE TITLE
Streaming still writes temporary files to disk

### ISSUE THREAD

**Issue by gtbremer** [tekmaven/nClam#28]
In issue #14 you stated...

> All you would need to do is download the file into a Stream object (or byte[]) in memory and then pass it to the SendAndScanFile(Stream sourceStream) or SendAndScanFile(byte[] fileData) methods of ClamClient. These methods never write the file to disk and stream them from memory.

However, as far as I can tell, ClamAV is still writing file contents to the temp folder even when SendAndScanFileAsync, which I can see uses INSTREAM when calling clamd. I'm not sure that this is a limitation of nClam but I'm wondering if there's some configuration setting to ensure that nothing is ever written to disk. Any ideas/suggestions?

**Comment by tekmaven** [comment]
To clarify, nClam will never persist the file to disk and will stream the data directly to ClamD. 

It seems you are saying that ClamD may temporarily store the file on disk when scanning it.  I'm not sure if it does this, but if that is wrong it would be great to clarify this for users - please reopen this issue and reference the ClamD docs so we can better document those calls.
