### ISSUE TITLE
Install-Package : Failed to add reference.

### ISSUE THREAD

**Issue by mickyinba** [tekmaven/nClam#29]
I ran this command in my Package Manager Console in VS: Install-Package nClam
My project's Target Framework = .NET Framework 4.5.2

Install-Package : Failed to add reference. The package 'nClam' tried to add a framework reference to 'System.IO' which was not found in the GAC. This is possibly a 
bug in the package. Please contact the package owners for assistance.
At line:1 char:1
+ Install-Package nClam
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by DHclly** [comment]
> I ran this command in my Package Manager Console in VS: Install-Package nClam
> My project's Target Framework = .NET Framework 4.5.2
> 
> Install-Package : Failed to add reference. The package 'nClam' tried to add a framework reference to 'System.IO' which was not found in the GAC. This is possibly a
> bug in the package. Please contact the package owners for assistance.
> At line:1 char:1
> 
> * Install-Package nClam
> * ```
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>   ```

The System.IO is Provide by Microsoft .net framework , it seems like your .net framework has not install correctly ， try to reinstall .net framework

**Comment by tekmaven** [comment]
We cut support for .NET Framework in the latest release.  If you need .NET Framework support, please take a source dependency.  The library is 1 self-contained file with no dependencies.
