### ISSUE TITLE
PingAsync() causing failures in Azure Function Runtime 3.0

### ISSUE THREAD

**Issue by PleaseStopAsking** [tekmaven/nClam#38]
It would seem that the current release of nClam (4.0.1) is unusable within v3.0 of the Azure Function Runtime due to an issue with the PingAsync() method. After going back and forth with Microsoft, we discovered that the method works just fine at v2.0 but not the new v3.0 runtime.

The issue only surfaces when an v3.0 Azure Function attempts to call the PingAsync() method against an IP that falls within RFC1918 which produces the error ```An attempt was made to access a socket in a way forbidden by its access permissions. [::ffff:172.16.1.4]:3310```.

The IP getting used is malformed and after digging into that, its because newer versions of dotnet core default to use ipv6 and you have to explicitly use ipv4 methods due to the Azure Function Runtime being dual stack (basically it has to be flagged to use ipv4 and this does happen if you use the proper method built into dotnet core, Ping.SendAsync)

I found the following method to handle either ipv6 or ipv4.  https://docs.microsoft.com/en-us/dotnet/api/system.net.ipaddress.maptoipv4?view=netcore-3.1

**Comment by PleaseStopAsking** [comment]
@bguidinger I assume this is the same issue you are referring to here, correct?

https://github.com/tekmaven/nClam/issues/37#issuecomment-619008010

**Comment by martinkearn** [comment]
I believe this is actually a .net Core 3.0 and above issue and can be an issue in any .net application, not just Functions. 

nClam uses `TcpClient` without specifying the address space. On .net core 3.0 and above, that means it defaults to IPv6. This causes an issue when you are working on an Azure VNET which does not support IPv6. 

The fix (as specified in issue #37 ) is to use `var clam = new TcpClient(AddressFamily.InterNetwork);` (which mandates IPv4) or even use something like

```
var clam = new TcpClient(AddressFamily.InterNetworkV6);
clam.Client.DualMode = true;
```

See
- https://github.com/MicrosoftDocs/azure-docs/issues/45991
- http://www.lybecker.com/blog/2018/08/23/supporting-ipv4-and-ipv6-dual-mode-network-with-one-socket/

I do not know if this library is alive any more and whether it is worth doing a PR for it? @tekmaven ?

**Comment by PleaseStopAsking** [comment]
@martinkearn I get the impression from the lack of updates/responses that your PR will be ignored as I believe this project is dead from an ongoing update perspective which is unfortunate.

Nevertheless, thanks for the clarification on the fix required. May have to fork and maintain my own copy moving forward unfortunately.

**Comment by tekmaven** [comment]
This fix is merged.  Will be releasing a new major nuget version shortly.
