### ISSUE TITLE
HTTP/1.1 400 Bad Request Connection: close

### ISSUE THREAD

**Issue by hlabanak** [tekmaven/nClam#50]
Good day 

Kindly assist, when I use the nClam nugget package am getting the the above mentioned error, however when I test the ClamAv Restful API, the response is successfull. When i ping hostname that I use in Postman it resolves successfully.
You're assistance would gratefully appreciated.

 var clam = new ClamClient("hostname", portnumber);

            var scanResult = await clam.SendAndScanFileAsync(fileBytes);

            switch (scanResult.Result)
            {
                case ClamScanResults.Clean:
                    ServiceOperation.Message = $"The file is clean! ScanResult:{scanResult.RawResult}";
                    break;
                case ClamScanResults.VirusDetected:
                    ServiceOperation.Message = $"Virus Found! Virus name: {scanResult.InfectedFiles.FirstOrDefault().VirusName}";
                    break;
                case ClamScanResults.Error:
                    ServiceOperation.Message = $"An error occured while scaning the file! ScanResult: {scanResult.RawResult}";
                    break;
                case ClamScanResults.Unknown:
                    ServiceOperation.Message = "Unknown scan result while scaning the file! ScanResult: {0}"+ scanResult.RawResult;
                    break;
            }

![image](https://user-images.githubusercontent.com/40229180/125913872-ea632b33-df35-4b89-8740-af4831625e52.png)

**Comment by hlabanak** [comment]
ClamAv was sitting on a different range, I hosted on the same range and it started working again, now its giving the below error:
Unable to write data to the transport connection: An established connection was aborted by the software in your host machine.

**Comment by tekmaven** [comment]
Hello, this library uses the TCP socket clamav listens on.  It does not use the HTTP API.
