### ISSUE TITLE
Please add .NET 3.5 packages to NuGet releases

### ISSUE THREAD

**Issue by gingters** [tekmaven/nClam#7]
Hi,

we use nClam, but we still need to produce .NET 3.5 runnable assemblies.
So we sadly cannot use the nClam NuGet package, but need to compile it ourselves for .NET 3.5.

It would be great, if the nuget package could also contain the assembly compiled against .NET 3.5 additionally to the .NET 4 version.

Would you consider this feasible?
We likely could also help to get this running if you could support us with additional information about how the release process looks like for this project.

**Comment by tekmaven** [comment]
No community members have taken this on and I do not wish to support older .NET builds.  Since the library is really just 1 file, you can source import it into your .NET 3.5 application.
